name: Spring Boot CI/CD

on:
 push:
    branches:
      - main

jobs:
 build:
    runs-on: ubuntu-latest

    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean install
      env:
        DB_HOST: ${{vars.DB_HOST}}
        DB_PORT: ${{vars.DB_PORT}}
        DB_NAME: ${{vars.DB_NAME}}
        DB_USER: ${{vars.DB_USER}}
        DB_PASSWORD: ${{vars.DB_PASSWORD}}
        APP_STORAGE_SERVICE_URL: ${{vars.APP_STORAGE_SERVICE_URL}}

    - name: Copy artifact to root
      run: cp target/${{ vars.JAR_FILE}} .
  
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.3.0

    - name: Login to DockerHub
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        push: true
        tags: palmerovicdev/storage-service:latest
        build-args: |
          DB_HOST: ${{vars.DB_HOST}}
          DB_PORT: ${{vars.DB_PORT}}
          DB_NAME: ${{vars.DB_NAME}}
          DB_USER: ${{vars.DB_USER}}
          DB_PASSWORD: ${{vars.DB_PASSWORD}}
          APP_STORAGE_SERVICE_URL: ${{vars.APP_STORAGE_SERVICE_URL}}
          JAR_FILE=${{ vars.JAR_FILE}}
          
    - name: Run Deployment Trigger
      run: |
        curl --request GET '${{secrets.DEPLOY_URL}}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
